// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export type PhotoCategory = 'about' | 'backgrounds' | 'couples' | 'engagement' | 'family' | 'graduation' | 'pets' | 'seniors' | 'travel' | 'wedding'

export type Photo = {
  id: string
  category: PhotoCategory
  /** Slug of the source folder — one real shoot. */
  shoot: string
  /** Path prefix; append `-${width}.webp` for a rendition. */
  src: string
  widths: number[]
  width: number
  height: number
  aspect: number
  /** Average colour, used as the pre-load background. */
  color: string
  /** 20px inline blur placeholder. */
  lqip: string
}

export const PHOTOS: Photo[] = [
  {
    "id": "about-ashley-main-street-5-of-1",
    "category": "about",
    "shoot": "about",
    "src": "/photos/about/ashley-main-street-5-of-1",
    "widths": [
      480,
      960
    ],
    "width": 1080,
    "height": 720,
    "aspect": 1.5,
    "color": "rgb(105 115 109)",
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABwAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JZQAANusLmZSJMAAA/qkr27jLflzL0XafW2wG+AcHBYcHFYjCaQ5ebIX179fx3BdaDMXoLh3u9KGMM7KZyAAA"
  },
  {
    "id": "pets-06-27-2024-puppies-108",
    "category": "pets",
    "shoot": "06-27-2024-puppies",
    "src": "/photos/pets/06-27-2024-puppies-108",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(73 80 37)",
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABQBACdASoUAA0APu1kqU2ppaOiMAgBMB2JZgC7MoMrZEmjkYJxjdrBRNekAP7u3PbmNDJMH68iIFpdXtlYwySgfCuKHsdE1jCf31bIv22suXXv0AA="
  },
  {
    "id": "pets-06-27-2024-puppies-110",
    "category": "pets",
    "shoot": "06-27-2024-puppies",
    "src": "/photos/pets/06-27-2024-puppies-110",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(71 71 33)",
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACQAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JZACsABjyWmYVKA3AAP7u3gMSPeg4vLgzZB7rlH9likooeULhzg/2CHKLdh891RrDCanhEAmkgasAAAA="
  },
  {
    "id": "pets-06-27-2024-puppies-128",
    "category": "pets",
    "shoot": "06-27-2024-puppies",
    "src": "/photos/pets/06-27-2024-puppies-128",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(94 111 69)",
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JaACdACBrB7wBq3DKI9eAAP7jAyKZUiOc3l4C5jSKHwWdRaY8H/npm9yLJsbejBJHZsozvJ7BsNnXQJgAAA=="
  },
  {
    "id": "pets-06-27-2024-puppies-134",
    "category": "pets",
    "shoot": "06-27-2024-puppies",
    "src": "/photos/pets/06-27-2024-puppies-134",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(57 74 41)",
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JZACdAB6DrZGzrou4UAD+7qFVYQ/dPz6f5dCPVINZ7iJO0NTYWsJHvxDIiCzT6ijcl/uQoN0bS4NKoAA="
  },
  {
    "id": "pets-06-27-2024-puppies-26",
    "category": "pets",
    "shoot": "06-27-2024-puppies",
    "src": "/photos/pets/06-27-2024-puppies-26",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(165 148 135)",
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASoUAA0APu1kqU2ppaQiMAgBMB2JZgC2yBjrUby1kbUgAP6NHvN8wXTgwSHai6RIZngb5PO7ha89Cz2jOr8VQAAA"
  },
  {
    "id": "wedding-img-5762-7",
    "category": "wedding",
    "shoot": "2022-06-10-grant-sara-wedding-rehearsal",
    "src": "/photos/wedding/img-5762-7",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(83 71 68)",
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACQAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JQBdgBDoLBaMVUs0AAP7pQvo5vlSg5vokj4jd7Vd5lLDboPKvcK7rlhzUwNekFSNKntyuR1uAg/sYwAA="
  },
  {
    "id": "wedding-img-5767-1",
    "category": "wedding",
    "shoot": "2022-06-10-grant-sara-wedding-rehearsal",
    "src": "/photos/wedding/img-5767-1",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(110 99 87)",
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBQCdASoUAB4APu1kp02ppaOiMAgBMB2JQBbZBDmZuPM9Y5j9+DAgQqTsfC+ArZj88IAA/vKe931zBF/r1iT5E3MCwm1zeArIOn+9SZM9PuIaAiiBYCMs2gxdgrhlIL1p7ICdUoHUFqAd/sAyWezSMh+G7x8U2Y2bUV1BdwFxXFeMkrHGZudyOq/kF/c+lDIYAAAA"
  },
  {
    "id": "wedding-img-5849-4",
    "category": "wedding",
    "shoot": "2022-06-10-grant-sara-wedding-rehearsal",
    "src": "/photos/wedding/img-5849-4",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(132 106 89)",
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQBACdASoUAA0APu1iqU2ppaQiMAgBMB2JYgCdMoAC/srcSlULLIF4AAD+zfMzHRA0R8qEv7NbPZdF4t40BCT5dWziis733St93Objy3PffeQpcDVlS7UDPOAAAA=="
  },
  {
    "id": "wedding-img-5947-5",
    "category": "wedding",
    "shoot": "2022-06-10-grant-sara-wedding-rehearsal",
    "src": "/photos/wedding/img-5947-5",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(98 84 76)",
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwBACdASoUAA0APu1orU6ppiSiMAgBMB2JagC7AB9SQEwhjpn/8Rh28EAA/un9M1jwy5pQRaBkgsPxhuJn4pKpzchzuaZUCvnGk7FCk0R8w3t/DDAIAA=="
  },
  {
    "id": "wedding-img-5958-6",
    "category": "wedding",
    "shoot": "2022-06-10-grant-sara-wedding-rehearsal",
    "src": "/photos/wedding/img-5958-6",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(54 49 44)",
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JYwC2yCHSyOvZPKAKAAD+8NiviXbrsqKcgXFKsrP1vX9O2wWFsw8Em7YAAA=="
  },
  {
    "id": "engagement-img-57132",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/img-57132",
    "widths": [
      480,
      960,
      1440
    ],
    "width": 1892,
    "height": 2400,
    "aspect": 0.7883,
    "color": "rgb(131 118 92)",
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADQBACdASoUABkAPu1qqVAppiOiqA1RMB2JYwDCgAtDw5SpoSchR+c3GFzhiG87MAD+6R2tFwJval84zeQe+UTiisMzicIlkOnpnXWpGSi5JkaFN5N0+A3lIqKT3lzoiSxGLJz5s1rLZ/s1GlbajnCMo+R3Z4XkNRDSaPXgAAA="
  },
  {
    "id": "engagement-img-58081",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/img-58081",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(91 91 91)",
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAwBQCdASoUAB4APu1srlEppiQiqAqpMB2JaQAALRQGFwCgUn6e5WiY6BXyVYEHwgYiAADMCMC2i4ityPyJC5Dn4VC9HTo9nAnqdmy8Uc7iKNNmdxpJ4+RX77MkV5bEa/4Cbd1U0kcjw8o/zxSji3AAAAA="
  },
  {
    "id": "engagement-img-60341",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/img-60341",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(82 82 82)",
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADQBACdASoUAB4APu1oq1AppaOisBgIATAdiWkAAC5xXz6RnX6f2/zrZg7PGIQtAAD+7FeDZWUa2AH7Gn46gtmErIWdylpz1yeSqcNXD5O96R30YFtBpQdHEVQx3pnD4qzzyarlXwW38aN+Gnka4a/GmKCRTElDD9NornMAAAA="
  },
  {
    "id": "engagement-june2022-114",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/june2022-114",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(134 117 95)",
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABwAwCdASoUAA0APu1kqU4ppaOiMAgBMB2JQBOgAvR6G/Ubq0QA/XdgYjDPZZ6tWk5caBH5WFgtMEW9xRi+3b1k8q4iCX1nYjq03H9nPsAAAA=="
  },
  {
    "id": "engagement-june2022-176",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/june2022-176",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(117 98 65)",
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwBACdASoUAA0APu1iqU2ppaOiMAgBMB2JZACdMoRwABb3z8ledeZEwIAA/oYzHDE8nZ2FETBEsOL1IDKMU/uLkObnjkNy8EFb1rIzLiaLUqYscCCya2wCQAA="
  },
  {
    "id": "engagement-june2022-185",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/june2022-185",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(136 109 81)",
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABwBQCdASoUAB4APu1qqk8ppiOiMBgIATAdiUAVhmX4LF64GUJxpA2Iej0wqV7gKy/oFqsAAN+x5fDeDtHWXIFje66XRh+BI+qPUTNTvdYazyNdHeobqwnHcGaS3zsl6Zdgjt3R/UPsZLMdCs5Vy4W9zle7MqS8JUKPI2V0oAA="
  },
  {
    "id": "engagement-june2022-207",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/june2022-207",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(107 92 58)",
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAwBQCdASoUAB4APu1qqk8ppiOiMBgIATAdiUATpmq4OHtOLxBL1uUHTnsqglME10MBAAD+zc7MjHl12YjFcSmME4uMHIzBLidMCyUDkKLHBsArXvuqLf5tkac4KcO+NAWdZX4AcVWZFxQI28LEusQFDmJcrbrAsAFbhpW17+UNyi/Bp8vjAAAA"
  },
  {
    "id": "engagement-june2022-208",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/june2022-208",
    "widths": [
      480,
      960,
      1440
    ],
    "width": 1600,
    "height": 2400,
    "aspect": 0.6667,
    "color": "rgb(134 120 91)",
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADwBACdASoUAB4APu1iqE2ppaOiMAgBMB2JQBOmUABNSLBQ7UHBVRxYUgUDJ5TzMgAA/txMvTfNNlmOlb9JqY4xsZkOKjH7lhTr7vSv9ZuXXivZiMSPRDJzhk3ClIGJ7mWJhF8D6Em7wh8LnnVlyJ3mUycSfQwLw9PNkMiXRWKnsn+qqyAAAA=="
  },
  {
    "id": "engagement-june2022-220",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/june2022-220",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(94 81 47)",
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAwCdASoUAA0APu1kqk4ppaQiMAgBMB2JYgCdACCvT1Yr5VOIsAD+vkALJhHFb6juHTlFoaHm6NjQ/SXSyDUdiOuytbX3k+ZZVntU15YAAA=="
  },
  {
    "id": "engagement-june2022-271",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/june2022-271",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(123 95 87)",
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADQBQCdASoUAB4APu1kq06ppaQiKA1RMB2JQBOmW9gpAoe5JGZGuX8H7Ej8ycYlqZ+Z+GlRFowAAP7VFOommeeymBmQ9qBcRPnfi6+xyCBE0KWwFPI7QBRF5tTss+IxInAWR9YFww9wiFuzgq6JeAfH3e0lylTjuuYddBm6Nn4/16MF5YuvJ7fCqQAAAA=="
  },
  {
    "id": "engagement-june2022-32",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/june2022-32",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(182 174 159)",
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQBQCdASoUAB4APuFapk2opSOiN/qoARAcCWMAwNwh2M/BNmFS5T3G9PTzpJfWCqiUAP7UNoHX9pBIRd2c9H+XSnIxkbWMjnoYYeKukEZL9apq2WwaJox0Q6GAUBzSsfhjFvkUGE8fwC+Ds2hOxhzyd5ShxmjVU/XgAA=="
  },
  {
    "id": "engagement-june2022-54",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/june2022-54",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(170 158 134)",
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JQBWABCXEg8DCZT/DZ+AA/tfI8Dc1tyVL80EEvg5LhZsBR60k7wW1/7RBIRFPVoNR23xiEwAAAA=="
  },
  {
    "id": "engagement-june2022-bw-111",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/june2022-bw-111",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(115 115 115)",
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAwCdASoUAA0APu1oqk6ppiQiMAgBMB2JaQAAG/Gok0RGvAAA+pyjlMDG862v9u6ycgJM/5bF6lLzycmVTO1CwI2cuDo7uAAAAA=="
  },
  {
    "id": "engagement-june2022-bw-82",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/june2022-bw-82",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(134 134 134)",
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwBACdASoUAB4APu1kq08ppSOiMBgIATAdiWkAAC4M9WBIU0gJhvlLGBSxOlPgAP7VD5bUqdyB21m377yPnTvqcudx24haxswW+wZ6RUmS9wNTc9uq/CzsLoxeOmwved0+nUhliDGDPAAA"
  },
  {
    "id": "engagement-june2022-bw-84",
    "category": "engagement",
    "shoot": "2022-06-22-sg-engagement",
    "src": "/photos/engagement/june2022-bw-84",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(128 128 128)",
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQBACdASoUAB4APu1krVAppSQisBgIATAdiWkAAC5pkPMKcG0mAVlVkIlHMc3iCAD+4AWzpA/vC21oXW20QHv09MJVExKQTtWCOhRZpz1JMhyk46FzdZMR8fKPsoGZZB97dBuyAgAAAA=="
  },
  {
    "id": "engagement-july2022-109",
    "category": "engagement",
    "shoot": "2023-08-04-mc-engagement",
    "src": "/photos/engagement/july2022-109",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(124 117 99)",
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAwCdASoUAA0APu1orU6ppiSiMAgBMB2JZACxDExJWwqDOBCyKf0iAP5PgtxqGgs510qUgu7HfGEzX7aCwFiqB+XMe5GauPpwQ+awx596iX9uyOwlMRMyxIDwLP4AAAA="
  },
  {
    "id": "engagement-july2022-49",
    "category": "engagement",
    "shoot": "2023-08-04-mc-engagement",
    "src": "/photos/engagement/july2022-49",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(115 116 105)",
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JZQC/OCGsrmLHeo/gsR0AAP7J3v8s32EqdfN4vStLyywYqOBKSCzJRkj1qYzjsPvtpvEFrXqgVAAA"
  },
  {
    "id": "engagement-july2022-50",
    "category": "engagement",
    "shoot": "2023-08-04-mc-engagement",
    "src": "/photos/engagement/july2022-50",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(100 104 86)",
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoUAA0APu1kqU4ppaOiMAgBMB2JYwAAUKdMQMjbYnjNigAA/k335thrPjdomlpWqjVzVPgF4+F2dLN0e//KrR/i5jgYvwx36L9po0AA"
  },
  {
    "id": "engagement-july2022-64",
    "category": "engagement",
    "shoot": "2023-08-04-mc-engagement",
    "src": "/photos/engagement/july2022-64",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(107 114 88)",
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAwCdASoUAA0APu1kqU4ppaOiMAgBMB2JQAALPJB35FydRHO1gAD6jL7qggGYwMnvqJ4A3yDR5JY3+fC/5hfnT6tpS/+phKYjtaJjdfsQEFAAAAA="
  },
  {
    "id": "engagement-mallorie-connor-28",
    "category": "engagement",
    "shoot": "2023-08-04-mc-engagement",
    "src": "/photos/engagement/mallorie-connor-28",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(81 83 70)",
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBQCdASoUAB4APu1gp02ppSOiMAgBMB2JQBftcdhRwcP6pFAqQoNBvdb+qJsTjr5qGVwA837esMvOCXEWOc7cBWqkz0M57AmXLrPr0+H2peAF6t1i68R0CJDUeg+dSQq4l83YMm9bYWVhFYY6yhPbmTbAcB6IJ3WYTLNRyMu9lVGrjUrOtMJtihAAAA=="
  },
  {
    "id": "engagement-mallorie-connor-31",
    "category": "engagement",
    "shoot": "2023-08-04-mc-engagement",
    "src": "/photos/engagement/mallorie-connor-31",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(99 99 82)",
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACwBACdASoUAB4APu1iqE4ppaOiMAgBMB2JYwDDNBukWhh2fUnipjq0n+HVdiegAP7JVzKuWKdyABBeGe2fuhzTs6tWFGa0mufWByL4vdlwJR7lLs+NpZD+MAdu3Xxjv5Q4egQr1Snjhu/UHihs4yR72GxXcw59VujRrswAAAA="
  },
  {
    "id": "engagement-mallorie-connor-33",
    "category": "engagement",
    "shoot": "2023-08-04-mc-engagement",
    "src": "/photos/engagement/mallorie-connor-33",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(93 93 93)",
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQBQCdASoUAB4APu1qsFCppaSiqAqpMB2JaQAALm2D+1IcXuTtWhV7gnfQef9lGa8AAP7ErtLIa519UZaJ0OMCNY9uP8YYj4fnRIJ+kMy5pjyRT0CUmGKmh6bAXoyjr79GbnuBpzgAAA=="
  },
  {
    "id": "seniors-elise-portrait-102",
    "category": "seniors",
    "shoot": "2023-09-17-elise-portraits",
    "src": "/photos/seniors/elise-portrait-102",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(103 97 92)",
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABwBQCdASoUAB4APu1ip06ppSMiMBgMATAdiWcAt7gL2dqZq0CEJ+6dwna2EtLeaVIUBNqQAP6nsuFKY217XrnA0hokcilFstlTtvPlMXK6slPm9T6EAkAEWoTvEr8HZwix9Iw7R2zlEVDDVqHRn64myGchnAAA"
  },
  {
    "id": "seniors-elise-portrait-121",
    "category": "seniors",
    "shoot": "2023-09-17-elise-portraits",
    "src": "/photos/seniors/elise-portrait-121",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(111 103 103)",
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQBACdASoUAB4APu1mq08ppaOiKA1RMB2JYwCdAArtk3paNGjeFwGZ1vFDkoKwAAD+5QR0hi6NRX0KAMMLjiW86ygFsN25IzW75jyug7CP9bKG6C0N3B8DYBVQRfKJxUfSAAhpQLn3DVAHUnw443yAAAA="
  },
  {
    "id": "seniors-elise-portrait-236",
    "category": "seniors",
    "shoot": "2023-09-17-elise-portraits",
    "src": "/photos/seniors/elise-portrait-236",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(148 149 149)",
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACQBQCdASoUAB4APuVgpk2pJaOiMAwBIByJQBajbIBwULxvuFW/EOi7r8W4D1zPEprorj2dgAD+sjd78BpvuHI5a/vST3UjevZlbxX0u6SKlWIF5yGAYblPgTCnoiprnCW+gEP18eZAJzKpFV0u6TO2N4oWSaGu45UHhqQquXfCpOEQERRr4AAA"
  },
  {
    "id": "seniors-elise-portrait-244",
    "category": "seniors",
    "shoot": "2023-09-17-elise-portraits",
    "src": "/photos/seniors/elise-portrait-244",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(174 173 167)",
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQBACdASoUAA0APu1iqU2ppaQiMAgBMB2JQBOmUABpWJq1+/QIZMzmQAD+kZGQLzCAyFDtG2elxXPsHWkmCYpVMQOXlbIYR7jErFVsCidVAAAA"
  },
  {
    "id": "seniors-elise-portrait-293",
    "category": "seniors",
    "shoot": "2023-09-17-elise-portraits",
    "src": "/photos/seniors/elise-portrait-293",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(145 143 130)",
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwBACdASoUAB4APuVipU2pJaOiMAwBIByJYwC7AB4Ch85g0OjMkIXO9MVlDTBG6wAA+9j4S2YFlJjpg7PviArYH2uky3i4SnH7mY5WQfEiWeSbmBBVUJCNpXpvRlRr+hInxM4tpicaEWjrSX4BP55kCY0vqAAA"
  },
  {
    "id": "seniors-elise-portrait-44",
    "category": "seniors",
    "shoot": "2023-09-17-elise-portraits",
    "src": "/photos/seniors/elise-portrait-44",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(91 90 76)",
    "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADQBQCdASoUAB4APu1qqU8ppiOiMBgIATAdiWMAw3d4ADnZL6JF932DH5DpWCnMB+ZCirNufEYAAP7BObQEDmK7g1wizNjgi1YJu7CaS+wn+in35iYLA0pcCGB8YmiyP/kr8lnhsFrFcl6QaRxq+XhLEQOIP5g/sIbqy/QSwzOBYAAA"
  },
  {
    "id": "seniors-elise-portrait-55",
    "category": "seniors",
    "shoot": "2023-09-17-elise-portraits",
    "src": "/photos/seniors/elise-portrait-55",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(121 116 97)",
    "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADwBACdASoUAB4APu1mrE+ppSQiMBgIATAdiUAXyQEhqT08ZbfJxLnCq5Kj923fRKAA/tdp5WBoU04wTdKSTfUxym8XM43rTE04PsQwS1vdNByVc3zfr8vHhgIxQqaBmxQi+TOx5Jr/4qhAWgwAzJhsQf5F1DKlKkUs+hmkEL4cRAAA"
  },
  {
    "id": "seniors-elise-portrait-80",
    "category": "seniors",
    "shoot": "2023-09-17-elise-portraits",
    "src": "/photos/seniors/elise-portrait-80",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(110 104 84)",
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABQBQCdASoUAB4APu1mqk+ppSOiMBgIATAdiWMAuwAPY/n6KM4T2zkf2whTsjldDCte+bgA/oiz5iIePXVarezqF+HJeZMvBN7W9dIcJMfH9AIlYTSgGtEKx3mQQd8fEhh9rjYLcEgJrYlZRCwIBYaQekypN2/AAAA="
  },
  {
    "id": "seniors-elise-portrait-87",
    "category": "seniors",
    "shoot": "2023-09-17-elise-portraits",
    "src": "/photos/seniors/elise-portrait-87",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(109 103 80)",
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoUAA0APu1iqk4ppaQiMAgBMB2JQBYdguKsw0a9tiYrEAD+rDN5A/8zC0O4vaxpkqnNSRwcTbw5mLV87mddHn69OjiC3jtl6ZzXAAAA"
  },
  {
    "id": "family-2024-05-18-grad-party-1",
    "category": "family",
    "shoot": "2024-05-03-graduation-family-portraits",
    "src": "/photos/family/2024-05-18-grad-party-1",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(84 84 49)",
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JZgC7ACG8TStndNLUggAA/tzpvOE5cmwGAvdeaNURtyhR6trlRtEtnGD45VQC/MfnPsSmdAaIAA=="
  },
  {
    "id": "family-2024-05-18-grad-party-120",
    "category": "family",
    "shoot": "2024-05-03-graduation-family-portraits",
    "src": "/photos/family/2024-05-18-grad-party-120",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 5615,
    "height": 3743,
    "aspect": 1.5001,
    "color": "rgb(122 115 76)",
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JZgCsAA6nuNDDetgA/krNmtJZCEBOPqmxBgbEhfFrBj9eeyLjNjB62B7MtXosdG6tPmvLzo+k5eUNEAA="
  },
  {
    "id": "family-2024-05-18-grad-party-133",
    "category": "family",
    "shoot": "2024-05-03-graduation-family-portraits",
    "src": "/photos/family/2024-05-18-grad-party-133",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(110 105 67)",
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JagCdAB2/b3TcacF2wADLSctlqOyauXF9MCV5d+DlJ+Xi0hevY/ZbHoqP+Hgz7UI90GEqfGpGuV5+o3AAAA=="
  },
  {
    "id": "family-2024-05-18-grad-party-155",
    "category": "family",
    "shoot": "2024-05-03-graduation-family-portraits",
    "src": "/photos/family/2024-05-18-grad-party-155",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(161 128 131)",
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQBACdASoUAA0APu1iqU2ppaOiMAgBMB2JagCdABcOXcTceiZX70VcAAD817kD2c1838Ib2rATHnRPbwDxKNmICYKWpDUqu3Lophkgx+Y2B0AA"
  },
  {
    "id": "family-2024-05-18-grad-party-196",
    "category": "family",
    "shoot": "2024-05-03-graduation-family-portraits",
    "src": "/photos/family/2024-05-18-grad-party-196",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 5481,
    "height": 3654,
    "aspect": 1.5,
    "color": "rgb(141 125 104)",
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAwCdASoUAA0APu1kqk4ppaQiMAgBMB2JQBOmUABpkJ2m4gxFAAD8cPZreMPIRhd49s1aaUjqnCqpnoYMHhVdDhmLFbATCJBJUYBsN8K9l2Wc0AA="
  },
  {
    "id": "family-2024-05-18-grad-party-223",
    "category": "family",
    "shoot": "2024-05-03-graduation-family-portraits",
    "src": "/photos/family/2024-05-18-grad-party-223",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(160 144 122)",
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JQBOgBDwj0MimmFxINQAA/siEDxhmNANtkWv/UvSOYpA4d+StRpdnfQlQQvQn70kQQNOScNCHz184AAA="
  },
  {
    "id": "family-2024-05-18-grad-party-238",
    "category": "family",
    "shoot": "2024-05-03-graduation-family-portraits",
    "src": "/photos/family/2024-05-18-grad-party-238",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(180 167 153)",
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JQBOgBDiT8N6o9MNjpgAA/pcbhTbLNxniDdysqOWQyaPjTHLpYpb95DYiLJB2D3ntC9AA"
  },
  {
    "id": "seniors-2024-07-05-park-practice-101",
    "category": "seniors",
    "shoot": "2024-05-03-forest-portrait",
    "src": "/photos/seniors/2024-07-05-park-practice-101",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(99 96 69)",
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwBACdASoUAA0APu1kqU4ppaOiMAgBMB2JYwCAAAiPh6kpEgmQ+NkWF2AA/uxIzfqvl8GOB487b69dLpqfU+3biFauKjv5k7l3tpEAAAA="
  },
  {
    "id": "seniors-2024-07-05-park-practice-193",
    "category": "seniors",
    "shoot": "2024-05-03-forest-portrait",
    "src": "/photos/seniors/2024-07-05-park-practice-193",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(74 76 72)",
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JaQAAW8doplzfhJT5wAD+8NSmf2VGKXtUJ8CZimgAnCiYScIThofaCf3htQgA"
  },
  {
    "id": "seniors-2024-07-05-park-practice-51",
    "category": "seniors",
    "shoot": "2024-05-03-forest-portrait",
    "src": "/photos/seniors/2024-07-05-park-practice-51",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(69 68 52)",
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwBQCdASoUAB4APu1oq02ppqQiMAgBMB2JYwC90CG+sGuSA+n3C6BSEGL0xKQoW1YCdeN37QAA/uPO82+t5+qAOfaVHPKItxw4sRi0h0aCcdv7gB4FM1tHAAg1v9YIrU62Btot7uIzD9G16WSRo3uofOEoegp9gYWN3LCJ1JMy9u4XvvYWAAAA"
  },
  {
    "id": "couples-am-27",
    "category": "couples",
    "shoot": "2024-09-28-delynn-s-wedding",
    "src": "/photos/couples/am-27",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(109 98 89)",
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQBQCdASoUAB4APu1qr1CppaQiqAqpMB2JZQC/OA9kxV56tqYrBjB0Tn7+50IGjTAAAP7XObZZ5Fsus+n6qFIxNB5xfBWw6fu+vxIoct1j5ZG0bzf3vwEnJWqdaONjtL7gDtQum/AyF8nlbpEdREVUlPClUaa/w4AAAA=="
  },
  {
    "id": "couples-am-29",
    "category": "couples",
    "shoot": "2024-09-28-delynn-s-wedding",
    "src": "/photos/couples/am-29",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(137 137 137)",
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAABwAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JaQAAUb3nqJTlkcAA/ADnzJ7u0tYQcweUgw/o93hMlijRoAy+rn0Mf3JCdsAA"
  },
  {
    "id": "couples-am-3",
    "category": "couples",
    "shoot": "2024-09-28-delynn-s-wedding",
    "src": "/photos/couples/am-3",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 3326,
    "height": 4989,
    "aspect": 0.6667,
    "color": "rgb(74 64 46)",
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQBQCdASoUAB4APuFgpk2opaOiMAwBEBwJYwAAXK+MOT1J6Hz6J3Ad9C+26WFHthIAAP7pGSfFIwDFa3veg7R/gF/btP/4dTy/2skN8FKwdTGDVA5remxDhGqOlnwNaQQgehk1uEAAAA=="
  },
  {
    "id": "couples-am-30",
    "category": "couples",
    "shoot": "2024-09-28-delynn-s-wedding",
    "src": "/photos/couples/am-30",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(145 145 145)",
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAwCdASoUAA0APu1kq04ppaQiMAgBMB2JaQAAUb3juIuNeYAA9ro6Xgts3pTpTKJ7hdP/jCQ6aIBDyEFUoyA9uf+smcn1zSAAAA=="
  },
  {
    "id": "couples-am-43",
    "category": "couples",
    "shoot": "2024-09-28-delynn-s-wedding",
    "src": "/photos/couples/am-43",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(144 134 123)",
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JYwCdMoAC/A/b5O7i3ZYwAM3zQXoSTstPN7XIGGelO01IjqfJnAT3bUW7HuOzIBRXWuJLauB6xVPoRUgAAA=="
  },
  {
    "id": "travel-austria-2025-32",
    "category": "travel",
    "shoot": "2025-06-10-europe",
    "src": "/photos/travel/austria-2025-32",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(121 131 125)",
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JQBOgBEA5o3mzSRZ0AP7eyuuXlTKp2MhFcoP055LT8Aquoarp+i8mHjCZrm2O2aEy0F7AAAA="
  },
  {
    "id": "travel-austria-2025-88",
    "category": "travel",
    "shoot": "2025-06-10-europe",
    "src": "/photos/travel/austria-2025-88",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(92 96 94)",
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JZwAANhowFALVTLuAAP7ne+fim7u4cWkoHq79oL8I2Tt17pxRJFAStbVoKBWIVWoCQpqyV77KP76FAAA="
  },
  {
    "id": "travel-italy-2025-186",
    "category": "travel",
    "shoot": "2025-06-10-europe",
    "src": "/photos/travel/italy-2025-186",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(132 115 107)",
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAwCdASoUAA0APu1kqU2ppaQiMAgBMB2JQBOmUABCf4wrwrvVIksYAOJyv34TMid5RmIwXKEulbA9EUGylmvPgEyM8XmK+ocWvoZtKMjmuAAA"
  },
  {
    "id": "travel-italy-2025-187",
    "category": "travel",
    "shoot": "2025-06-10-europe",
    "src": "/photos/travel/italy-2025-187",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(138 121 113)",
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoUAA0APu1kqk4ppaQiMAgBMB2JQBOnKAANvjAGm+OR/WoAAP1C2yhcFRaA9zaB/UqYFSPeSRmD5l177iKPhJsnBrLy/9Fs9wINToj2YkQAAA=="
  },
  {
    "id": "travel-italy-2025-200",
    "category": "travel",
    "shoot": "2025-06-10-europe",
    "src": "/photos/travel/italy-2025-200",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(157 140 111)",
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwBACdASoUAA0APu1kqk4ppaQiMAgBMB2JQBOmUABr24d96271XOFV4AAA3mBdYzA9UUJ//FWRboeZYcZwAC0m3in1LuDBsIGtjEgRx6h4mFV51GgAAA=="
  },
  {
    "id": "travel-italy-2025-339",
    "category": "travel",
    "shoot": "2025-06-10-europe",
    "src": "/photos/travel/italy-2025-339",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(187 188 189)",
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAwCdASoUAA0APu1yrU+pp6QiMAgBMB2JZwAAW78zwCg02gAA/pFFJjm88t0BU8vvujfV9MHcmpymKsXYhxSmx9ZWv/Aja8AAAA=="
  },
  {
    "id": "graduation-em-grad-101",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-101",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 11167,
    "height": 7445,
    "aspect": 1.4999,
    "color": "rgb(150 131 106)",
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACQAwCdASoUAA0APu1mqk4ppaOiMAgBMB2JQBOgBFHBF09F+a66AP7c21ycrEBGHvFdr4gzjFl214jE/Hr4PYVt4sHVDcAfA1wyMNwJjzAAAA=="
  },
  {
    "id": "graduation-em-grad-103",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-103",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 12000,
    "height": 8000,
    "aspect": 1.5,
    "color": "rgb(149 135 106)",
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoUAA0APu1iqk4ppaQiMAgBMB2JYgCw7BmjbsKYIjJfrorAAP5D7ter+2f9MgnceGcovVgqhoFsCY7u6DeTw94Nq1QYGYsQW6lJpbcZtYAAAA=="
  },
  {
    "id": "graduation-em-grad-141",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-141",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 12000,
    "height": 8000,
    "aspect": 1.5,
    "color": "rgb(120 112 82)",
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwBACdASoUAA0APu1iqk2ppaQiMAgBMB2JQBWGUI4AA9rj4iqDUVd/KgAA/unSvaS7mAc74B3N1fDBNvQ1pSRzlr7Ye+iawdI9HAP8jfeJvl0TiQAAAA=="
  },
  {
    "id": "graduation-em-grad-194",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-194",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(85 85 85)",
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAABwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JaQAAPXY7NyvfEAAA/ryFDmKeJ5vQ+Dr13+aqsAI8Xn6zPHAAAA=="
  },
  {
    "id": "graduation-em-grad-198",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-198",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(95 95 95)",
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAwCdASoUAA0APu1mqk4ppaOiMAgBMB2JaQAAWm/fGTAA/trGbi4Pxsf9W3jsrrvnJnSBs0c9xpv3XfZuKlv3ZgAAAA=="
  },
  {
    "id": "graduation-em-grad-201",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-201",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(87 87 87)",
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAABQAwCdASoUAA0APu1kqU4ppaOiMAgBMB2JaQAAWze8KvqoyAD+5FkHnIFLD18/VhEFAcHIwoeNS3ocz8PaHxAAAAA="
  },
  {
    "id": "graduation-em-grad-233",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-233",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(170 168 167)",
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACQBACdASoUAB4APtFWoU2oJKMiN+gBABoJZQC7ACTWYBO+ORWB4ugZeOZ6bAAA/vHXzvVAl2ZnuMFCh4/vRWrtOGULZ2YrZQcfJX+TEUCuZiiURKs10ocA6rTehjlMRs6HRuxiE2rrLZwFcBGThEwlgAA="
  },
  {
    "id": "graduation-em-grad-234",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-234",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(171 171 171)",
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABwBACdASoUAB4APtleo02oJaMiN/qoAQAbCWkAAELWfOv7H/JVUsk+YeMrAAD+78za33whx13ZObfa/mGStnq03WC/fhDjGFrduM0G5w9HCc/iM5LTf1MgAAA="
  },
  {
    "id": "graduation-em-grad-253",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-253",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 8000,
    "height": 12000,
    "aspect": 0.6667,
    "color": "rgb(107 100 73)",
    "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBQCdASoUAB4APuVgpU2pJaOiMAwBIByJQBYdhDia+vpAbqRanQa2Wi87/RTgscwAANyRF4lrrE9sHMn4P47aghzFwyFXUQv2I6C1dCFGpdY97+akNMQtm9dNaNPEci5sWy+KflXHC7MFvkOwzX/OiJmBbKZ394G0kRz7tDGQAAAA"
  },
  {
    "id": "graduation-em-grad-269",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-269",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 8000,
    "height": 12000,
    "aspect": 0.6667,
    "color": "rgb(94 92 67)",
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwBQCdASoUAB4APu1oq04ppiQiMAgBMB2JYwDG9BdQlTiM2EXwVoHGb21W5k3E+lWSgAD+q1sQ4NW0cMw8Ca9+tOWVwSCcn6OtdKaHSJtukVEU93MabsZm+t6KNU5BNHtu16+s6GgvVPmoM8ce9WIfM7BOzLcVGIAAAA=="
  },
  {
    "id": "graduation-em-grad-278",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-278",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(99 96 70)",
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADwBACdASoUAB4APt1cpE2opSOiN/qoARAbiUAWHYE1/ane3JnlFvwOEyDTjwcieIAA1LmYra/MizfJHu9o6bU7qG9aYzwgNhKaehJldpkZXbQhQESUPQ1qrIiLtnRcltRjExtActpxlfM2BHuTBqt1Z/XbafpcAAA="
  },
  {
    "id": "graduation-em-grad-279",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-279",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(78 78 78)",
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwBACdASoUAB4APtlco02oJaMiN/qoAQAbCWkAADg89Sg4O1RWic/f9r0AGKM6esAA/Ry29TH9eQ8HqqXnn88ifm+DlZYqu+pWV4VuH1XiFrKxHozTzA/NQ0CDAe0NIAAAAA=="
  },
  {
    "id": "graduation-em-grad-38",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-38",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "color": "rgb(140 135 126)",
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACwBACdASoUAB4APu1iq02ppaQiMBgMATAdiWUAAA47S/QNy1LG/VatgRcfrvcAAPyC6FotgvxFwq+ZrSkeTJcnSf9CR/2Yb2iWSfOf4tM3azFw+MyrR5/iSAmR40UtLpsovchP+v0z9hSAAAA="
  },
  {
    "id": "graduation-em-grad-48",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-48",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 8000,
    "height": 12000,
    "aspect": 0.6667,
    "color": "rgb(125 117 108)",
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQBACdASoUAB4APu1oqU+ppiOiKA1RMB2JYwC3uAyFlWSRcbqyFkRUjH4Q8whdKgD9zbbSO4eJGO5IRuW4qgI7DAPhF+XzVfD+Ax2Oh7Jf3WjJEc+bZLWEPTlfecOMk+vGcDDAsEGYoAAA"
  },
  {
    "id": "graduation-em-grad-61",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-61",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(142 138 133)",
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAABQAwCdASoUAA0APu1kqU2ppaQiMAgBMB2JaQAATsU+X6AQAADvurjdvBYzOS+P17xVcoNUicXp6mpcP1msymGRudLMAAAA"
  },
  {
    "id": "graduation-em-grad-64",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-64",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(147 138 129)",
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JYwC7ABSXYk2rzSIAAMzxrGvEzY0ZzvM8nE4suByKsKfpbljubPJpOKFVmTe77V7UQAAA"
  },
  {
    "id": "graduation-em-grad-76",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-76",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 12000,
    "height": 8000,
    "aspect": 1.5,
    "color": "rgb(141 134 117)",
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JZQCw7CHR0qh6f8KPuYAA/tDr6mb8Cae2rt+zr3+RiA/MADt4uTYs6Y+QgAAA"
  },
  {
    "id": "graduation-em-grad-78",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-78",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 12000,
    "height": 8000,
    "aspect": 1.5,
    "color": "rgb(141 130 113)",
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JYwC06CHw+RpRHXbi7gAA/sG3Kc+JhHlRGFbfi7LXAu/Ey/geiS6wvPoIj0RFTSVAAA=="
  },
  {
    "id": "graduation-em-grad-80",
    "category": "graduation",
    "shoot": "2026-05-09-elise-grad-pictures",
    "src": "/photos/graduation/em-grad-80",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 12000,
    "height": 8000,
    "aspect": 1.5,
    "color": "rgb(140 133 115)",
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQBACdASoUAA0APu1iqU2ppaQiMAgBMB2JZQCsACIfxWxAq1IdgRkBYAD+wGZ1WO1MUyWQWOEucJH49rD23RaU2xAAAA=="
  },
  {
    "id": "backgrounds-2024-07-05-park-practice-122",
    "category": "backgrounds",
    "shoot": "backgrounds",
    "src": "/photos/backgrounds/2024-07-05-park-practice-122",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(18 23 13)",
    "lqip": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAwCdASoUAA0APu1kqU2ppaOiMAgBMB2JZwAAW+xaOYKdOPRyQAD+8qPGaPSSwRzz9qtL3dfSzAAA"
  },
  {
    "id": "backgrounds-2024-07-05-park-practice-127",
    "category": "backgrounds",
    "shoot": "backgrounds",
    "src": "/photos/backgrounds/2024-07-05-park-practice-127",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(46 56 38)",
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAwCdASoUAA0APu1kq04ppaQiMAgBMB2JZQC06CHwX1fgPufB6WvAAP7uh8GEMuzd/YAZ8MnG5jTQ7aiwH5bQWGpNSwAA"
  },
  {
    "id": "backgrounds-2024-07-05-park-practice-188",
    "category": "backgrounds",
    "shoot": "backgrounds",
    "src": "/photos/backgrounds/2024-07-05-park-practice-188",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(96 106 85)",
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoUAA0APu1kqU2ppaQiMAgBMB2JYgCw7BZLRxmK+l4cNIAA/pFjkl09ITYOATTQnD6wnMysatoh4gpK0fNAc9pirwdJchahz6KwAA=="
  },
  {
    "id": "backgrounds-italy-2025-167",
    "category": "backgrounds",
    "shoot": "backgrounds",
    "src": "/photos/backgrounds/italy-2025-167",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(140 130 108)",
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JQBOgBDuK0dxi97fq/DgA/u1/9/vh2ZlOpE2rt1UN+wr7Y0fXc5Mva3HzZOnzMDjb7hDQAAA="
  },
  {
    "id": "backgrounds-italy-2025-196",
    "category": "backgrounds",
    "shoot": "backgrounds",
    "src": "/photos/backgrounds/italy-2025-196",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(140 115 90)",
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JQBOmUABdDsZtJgAA7x7l/q3aUUqgibWbEOSOeAVxmLAvCMAyQetPnzPuX/tc20CVN9LfTIrSKe6eUAA="
  },
  {
    "id": "backgrounds-italy-2025-318",
    "category": "backgrounds",
    "shoot": "backgrounds",
    "src": "/photos/backgrounds/italy-2025-318",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(95 97 80)",
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoUAA0APu1kq04ppaQiMAgBMB2JZQDE2BVDymofVWt574AA/u9NzKdN9eKbmd2Hf23VXhPwNbv9l8W6TQ6OL6/K7EHllpZYS7jHrhaKAAA="
  },
  {
    "id": "backgrounds-italy-2025-319",
    "category": "backgrounds",
    "shoot": "backgrounds",
    "src": "/photos/backgrounds/italy-2025-319",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(132 134 132)",
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAABwAwCdASoUAA0ALrV2u12jqampiYC0SzgABi/8rqUixdfRhxgA/uqw2JXQSqpixuh9tDJanrbRKFkPOEAAAA=="
  },
  {
    "id": "backgrounds-italy-2025-320",
    "category": "backgrounds",
    "shoot": "backgrounds",
    "src": "/photos/backgrounds/italy-2025-320",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(53 52 35)",
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JZQDG9Aqa+M8JAAD+7p9g0fFJry/n/YHn79eo4fwUibpkZZJ711UdalkHwlKD0FeAAA=="
  },
  {
    "id": "backgrounds-italy-2025-324",
    "category": "backgrounds",
    "shoot": "backgrounds",
    "src": "/photos/backgrounds/italy-2025-324",
    "widths": [
      480,
      960,
      1440,
      2000,
      2600
    ],
    "width": 6000,
    "height": 4000,
    "aspect": 1.5,
    "color": "rgb(129 133 134)",
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAwCdASoUAA0APu1krU6ppaSiMAgBMB2JZwDG9CFqGKDWQ6T4AAD+8fSDuVFO+V8KejCOntGT9lRxIpjeg+6+sylgAA=="
  }
]

export const BY_ID = Object.fromEntries(PHOTOS.map((p) => [p.id, p])) as Record<string, Photo>

export const BY_SHOOT = PHOTOS.reduce<Record<string, Photo[]>>((acc, p) => {
  ;(acc[p.shoot] ??= []).push(p)
  return acc
}, {})
